### ISSUE TITLE
DeploymentOptimization.adjust method calls set_resource_requirements with wrong parameter

### ISSUE THREAD

**Issue by linkous8** [opsani/servox#78]
https://github.com/opsani/servox/blob/b4fe0f84ea069a541698dfcb8e6deaf170580da5/servo/connectors/kubernetes.py#L1796-1800

`name` on line 1799 should be `resource_name`

**Comment by blakewatters** [comment]
Thanks! This is one I had caught on a branch and totally missed that it was still hanging out on master.
